---
name: "Build, Lint and Test"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make race
